### PR TITLE
fix: gate no_storage import within test scope

### PR DESCRIPTION
**Pull request by 0xObsidian**
### This PR:
* Fixes linter errors by properly gating `no_storage` import within test scope
* Ensures `no_storage` module is only imported when the feature flag is enabled

### Key places to review:
* `src/availability.rs`
* Feature gate implementation

### Things tested
* Verified linter errors are resolved
* Confirmed all tests pass with `cargo nextest run --all-features`

### Implementation Details
The `no_storage` module is feature-gated behind `no-storage`, but was being imported at the test module level, causing linter errors when the feature was not enabled. The fix:

* Moved `no_storage` import inside the specific test that uses it
* Added feature gate to the test: `#[cfg(all(not(target_os = "windows"), feature = "no-storage"))]`
* Kept other tests in the module accessible without the feature

Previous Error:
```
unresolved import `crate::data_source::storage::no_storage`
```

### CODE REVIEW

**Review by imabdulbasit — APPROVED** [review]

**Comment by imabdulbasit** [comment]
Thank you fo your contribution. Please merge main or rebase to fix clippy errors on CI

**Comment by 0xObsidian** [comment]
> Thank you for your contribution. Please merge main or rebase to fix clippy errors on CI

Hi @imabdulbasit  Thanks for the reply, I will do it today evening

**Comment by 0xObsidian** [comment]
Hi @imabdulbasit, it's done

**Comment by imabdulbasit** [comment]
We have removed the NoStorage feature completely so I am going to close this PR

**Pull request closed without merging**
